spring.application.name=gco

# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
server.port=8080

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/gco_fidelizacion?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURACIÓN JPA / HIBERNATE
# ===============================
# update: crea o actualiza las tablas automáticamente según las clases @Entity
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de Spring las sentencias SQL que Hibernate ejecuta
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

# Generar nombres de tablas y columnas respetando snake_case automáticamente
spring.jpa.properties.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
